// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4FWpf9wVj2fiMr1ge05eEhnsNhmFdoso',
    appId: '1:395048552322:android:a608dcb83c07668fed719b',
    messagingSenderId: '395048552322',
    projectId: 'desmokerizer',
    databaseURL: 'https://desmokerizer-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'desmokerizer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoOWwg27pXd7wnlcwUv7oWzEHECI3YpW8',
    appId: '1:395048552322:ios:7349c1f48b0d8d02ed719b',
    messagingSenderId: '395048552322',
    projectId: 'desmokerizer',
    databaseURL: 'https://desmokerizer-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'desmokerizer.appspot.com',
    iosClientId: '395048552322-g7oo09t5qr7470d663vs8nl18o4shof9.apps.googleusercontent.com',
    iosBundleId: 'com.example.desmokrizer',
  );
}
